log:
  level: debug

plugins:
  - tag: custom_hosts
    type: hosts
    args:
      entries:
        - "archrouter.top 148.135.78.154 2607:f130:0:160::8021:c03a"

  - tag: dns_rule
    type: sequence
    args:
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept

      - matches:
        - qname &/etc/mosdns/rules/geosite_private.txt
        exec: reject 3

      - exec: query_summary

      - exec: cache 8192
      - matches: has_resp
        exec: accept

      - matches:
        - qname &/etc/mosdns/rules/geosite_cn.txt
        exec: forward https://223.5.5.5/dns-query
      - matches: has_resp
        exec: accept

      - exec: forward https://1.1.1.1/dns-query
      - matches: has_resp
        exec: accept

  - tag: udp_server
    type: udp_server
    args:
      entry: dns_rule
      listen: "[::]:53"
