log:
  level: debug

plugins:
  # 自定义域名列表
  - tag: custom_dns
    type: hosts
    args:
      entries:
        - "archrouter.top 148.135.78.154 2607:f130:0:160::8021:c03a"
        # - "popads.net 216.21.13.12 216.21.13.13"

  # 拦截域名集合
  - tag: domain_block
    type: domain_set
    args:
      exps:
        - "domain:minecraft.fandom.com"
      files:
        - "/etc/mosdns/rules/reject-list.txt"

  # 直连域名集合
  - tag: domain_direct
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/direct-list.txt"

  # 直连域名转发器
  - tag: dns_direct
    type: forward
    args:
      upstreams:
        - tag: ali_ipv4_https
          addr: https://223.5.5.5/dns-query
          enable_http3: false
          enable_pipeline: true

        - tag: adguard_ipv4_https
          addr: https://94.140.14.14/dns-query
          enable_http3: false
          enable_pipeline: true

  # 默认域名转发器
  - tag: dns_proxy
    type: forward
    args:
      upstreams:
        - tag: cloudflare_ipv4_https
          addr: https://1.1.1.1/dns-query
          socks5: "127.0.0.1:10808"
          enable_http3: false
          enable_pipeline: true

        - tag: adguard_ipv4_https
          addr: https://94.140.14.14/dns-query
          socks5: "127.0.0.1:10808"
          enable_http3: false
          enable_pipeline: true

  - tag: dns_rules
    type: sequence
    args:
      # 自定义域名解析
      - exec: $custom_dns
      - matches: has_resp
        exec: mark 100
      - matches: mark 100
        exec: query_summary [QUERY custom]
      # - matches: mark 100
      #   exec: debug_print [QUERY_custom_debug]
      - matches: mark 100
        exec: accept

      # 域名拦截
      # - matches:
      #   - qname $domain_block
      #   exec: mark 200
      # - matches: mark 200
      #   exec: query_summary [QUERY block]
      # - matches: mark 200
      #   exec: debug_print [QUERY_block_debug]
      # - matches: mark 200
      #   exec: reject 3

      # 域名缓存
      - exec: cache 8192
      - matches: has_resp
        exec: mark 300
      - matches: mark 300
        exec: query_summary [QUERY cache]
      # - matches: mark 300
      #   exec: debug_print [QUERY_cache_debug]
      - matches: mark 300
        exec: accept

      # 国内域名解析
      - matches:
        - qname $domain_direct
        exec: mark 400
      - matches: mark 400
        exec: $dns_direct
      - matches: has_resp
        exec: query_summary [QUERY direct]
      # - matches: mark 400
      #   exec: debug_print [QUERY_direct_debug]
      - matches: mark 400
        exec: accept

      # 默认域名解析
      - exec: $dns_proxy
      - matches: has_resp
        exec: mark 500
      - matches: mark 500
        exec: query_summary [QUERY proxy]
      # - matches: mark 500
      #   exec: debug_print [QUERY_proxy_debug]
      - matches: mark 500
        exec: accept

# DNS UDP服务器
  - tag: udp_server
    type: udp_server
    args:
      entry: dns_rules
      listen: "[::]:53"
# DNS TCP服务器
  - tag: tcp_server
    type: tcp_server
    args:
      entry: dns_rules
      listen: "[::]:53"
