log:
  level: debug

plugins:
  # 自定义域名列表
  - tag: custom_dns
    type: hosts
    args:
      entries:
        - "archrouter.top 148.135.78.154 2607:f130:0:160::8021:c03a 2607:f130:0:160::5e7:8d3b"

  # 拦截域名集合
  - tag: domain_block
    type: domain_set
    args:
      exps:
        - "domain:minecraft.fandom.com"
      files:
        - "/etc/mosdns/rules/reject-list.txt"

  # 直连域名集合
  - tag: domain_direct
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/direct-list.txt"

  # 直连域名转发器
  - tag: dns_direct
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: ali_ipv4_https
          addr: https://223.5.5.5/dns-query
          enable_pipeline: true
        - tag: ali_ipv6_https
          addr: https://[2400:3200::1]/dns-query
          enable_pipeline: true

  # 默认域名转发器
  - tag: dns_proxy
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: cloudflare_ipv4_https
          addr: https://dns.cloudflare.com/dns-query
          dial_addr: "1.1.1.1"
          enable_pipeline: true
        - tag: cloudflare_ipv6_https
          addr: https://dns.cloudflare.com/dns-query
          dial_addr: "2606:4700:4700::1111"
          enable_pipeline: true
        - tag: adguard_ipv4_https
          addr: https://dns.adguard-dns.com/dns-query
          dial_addr: "94.140.14.14"
          socks5: "[::1]:10900"
          enable_pipeline: true
        - tag: adguard_ipv6_https
          addr: https://dns.adguard-dns.com/dns-query
          dial_addr: "2a10:50c0::ad1:ff"
          socks5: "[::1]:10900"
          enable_pipeline: true
        - tag: quad9_ipv4_https
          addr: https://dns.quad9.net/dns-query
          dial_addr: "2620:fe::fe"
          socks5: "[::1]:10900"
          enable_pipeline: true
        - tag: quad9_ipv6_https
          addr: https://dns.quad9.net/dns-query
          dial_addr: "2620:fe::fe"
          socks5: "[::1]:10900"
          enable_pipeline: true
        - tag: google_ipv4_https
          addr: https://dns.google/dns-query
          dial_addr: "8.8.8.8"
          socks5: "[::1]:10900"
          enable_pipeline: true
        - tag: google_ipv6_https
          addr: https://dns.google/dns-query
          dial_addr: "2001:4860:4860::8888"
          socks5: "[::1]:10900"
          enable_pipeline: true

  - tag: dns_rules
    type: sequence
    args:
      # 自定义域名解析
      - exec: $custom_dns
      - matches: has_resp
        exec: mark 100
      - matches: mark 100
        exec: query_summary [QUERY custom]
      - matches: mark 100
        exec: accept

      # 域名拦截
      - matches:
        - qname $domain_block
        exec: mark 200
      - matches: mark 200
        exec: query_summary [QUERY block]
      - matches: mark 200
        # exec: reject 3
        exec: accept

      # 域名缓存
      - exec: cache 8192
      - matches: has_resp
        exec: mark 300
      - matches: mark 300
        exec: query_summary [QUERY cache]
      - matches: mark 300
        exec: accept

      # 国内域名解析
      - matches:
        - qname $domain_direct
        exec: mark 400
      - matches: mark 400
        exec: $dns_direct
      - matches: has_resp
        exec: query_summary [QUERY direct]
      - matches: mark 400
        exec: accept

      # 默认域名解析
      - exec: $dns_proxy
      - matches: has_resp
        exec: mark 500
      - matches: mark 500
        exec: query_summary [QUERY proxy]
      - matches: mark 500
        exec: accept

# DNS UDP服务器
  - tag: udp_server
    type: udp_server
    args:
      entry: dns_rules
      listen: "[::]:53"
# DNS TCP服务器
  - tag: tcp_server
    type: tcp_server
    args:
      entry: dns_rules
      listen: "[::]:53"
